apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-site-deployment
  labels:
    app: hugo-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-site
  template:
    metadata:
      labels:
        app: hugo-site
    spec:
      containers:
        - name: hugo-site
          image: carltonj2000/lke-example:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
