apiVersion: v1
kind: Service
metadata:
  name: hugo-site-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: hugo-site
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hugo-site
  sessionAffinity: None
